baekjoon/chaeeun/1037_week4.py
리스트 변환: O(N)
정렬: O(N logN)
👉 **O(N logN)**
파이썬의 map함수를 사용해봤다. 입력받은 데이터를 지정한 함수로 처리해주는 함수이다.
💬주절주절💬
처음 생각했던건 map을 사용하지 않고 for문을 도는 거였다~
1. 문자열을 splite하여 리스트로 저장
2. 새로운 빈 리스트를 생성하고 for문을 돌면서 int로 변환해준 다음에 리스트에 넣어준다.
근데 뭔가 좋은 방법이 있을 것 같아서 찾아본 후 map으로 바꿨다
=> [week4-BAEKJOON] 약수

leetcode/chaeeun/week5-contains_duplicate.py
👉O(N)
모든 요소를 돌면서 확인
dictionary 복습했다~
=> [week5-LEETCODE] contains_duplicate

leetcode/chaeeun/week5-valid_anagram.py
👉 O(n)
for key in dict명.keys()
for value in dict명.values() 
for key, value in dict명.itmes()
=> [week5-LEETCODE] valid_anagram

leetcode/chaeeun/week5-concatenation_of_array.py
n개의 요소를 복사해야하므로 👉O(n)
문제를 잘못봐서 n개의 개수만큼 복사해야하는 줄 알았다.
참고로 array의 길이를 알 기 위해서는 len(array) 해주어야 한다!!
=> [week5-LEETCODE] concatenation_of_array

leetcode/chaeeun/week5-replace_elements_with_greatest_element_on_right_side.py
👉 O(N)
처음에는 앞에서부터 처리하려했는데 시간초과가 날 것 같다는 느낌이 들었는데 역시나! 시간초과가 났다.
뒤에서부터 처리해야 했다.
=> [week5-LEETCODE] Replace Elements with Greatest Element on Right Side

leetcode/chaeeun/week5-is_subsequence.py
👉O(n)
순서가 있는 건 줄 몰랐다! 문제를 잘 보자.
그리고
```python
if s_length == 0:
return True
```
를 안해주면 `IndexError: string index out of range`에러가 나는데
이유는 `if char == s[i]`를 처리할 때 `s[0]`이 없기 때문에 에러가 난다
=> [week5-LEETCODE] is_subsequence

leetcode/chaeeun/week5-length_of_last_word.py
=> [week5-LEETCODE] length_of_last_word

README.md
week6 - update README.md table!
=> week6 - update README.md table!

week6-12944.py
=> [week6-PROGRAMMERS] 평균 구하기

programmers/chaeeun/week6-12937.py
=> [week6-PROGRAMMERS] 짝수와 홀수

programmers/chaeeun/week6-87389.py
=> [week6-PROGRAMMERS] 나머지가 1이 되는 수 찾기

programmers/chaeeun/week6-12925.py
O(문자열길이)
int()를 사용하지 않고는 어떻게 풀까
다른 사람의 풀이를 보다가 혼공파에서 봤던 `enumerate`를 활용한 코드를 봤다. 복습 굿
```py
def strToInt(str): 
result = 0
for idx, number in enumerate(str[::-1]):
if number == '-':
result *= -1
else:
result += int(number) * (10 ** idx)
return result
```
enumerate는 리스트의 요소를 반복할 때 현재 인덱스가 몇 번째인지 확인해야 하는 경우에 쉽게 작성할 수 있도록 파이썬에서 제공하는 함수이다~
`::-1`은 reverse 시켜주는 역할을 한다
=> [week6-PROGRAMMERS] 문자열을 정수로 바꾸기

programmers/han/week6/week6-나머지가1이되는수찾기.py, programmers/han/week6/week6-문자열을 정수로 바꾸기.py, programmers/han/week6/week6-약수의합.py
[week6-PROGRAMMERS] 나머지가 1이 되는 수 찾기, 문자열을 정수로 바꾸기, 약수의 합
O(n) => 인자 값의 길이에 맞춰 이루어지는 로직
여러 문법들을 활용하여 알아두도록 하자
=> [week6-PROGRAMMERS] 나머지가 1이 되는 수 찾기, 문자열을 정수로 바꾸기, 약수의 합

programmers/chaeeun/week6-12928.py
=> [week6-PROGRAMMERS] 약수의 합

programmers/chaeeun/week6-12954.py
👉 **O(n)**
```py
return [i * x + x for i in range(n)]
```
한 줄로 끝낼 수 있다. 이런 생각은 어떻게 하는 걸까~
=> [week6-PROGRAMMERS] x만큼 간격이 있는 n개의 숫자

baekjoon/chaeeun/week7-1152.py
=> [week7-BAEKJOON] 단어의 개수

baekjoon/seongdeok/week7/week7_1157.py
O(n) => 문자의 길이만큼 반복문을 돌고 다시 한번 최대 값을 찾기 때문에 2n -> n 이다 
문제를 잘 못보고 upper()이 아닌 casefold()를 사용함. 대소문자 무시하는 구문 (찾아봄)
=> [week7-BAEKJOON] 단어 공부

baekjoon/chaeeun/week7_2439.py
=> [week7-BAEKJOON] 별찍기-2

README.md, baekjoon/seongdeok/week7/week7_1157.py
=> week8 - Readme Update

baekjoon/chaeeun/week7_2577.py
=> [week7-BAEKJOON] 숫자의 개수

baekjoon/chaeeun/week7_2675.py
=> [week7-BAEKJOON] 문자열 반복

programmers/chaeeun/week8_30.py
=> [week8-PROGRAMMERS] 자릿수 더하기

baekjoon/seongdeok/week7/week7_2439.py, baekjoon/seongdeok/week7/week7_2562.py, baekjoon/seongdeok/week7/week7_2576.py, baekjoon/seongdeok/week7/week7_2577.py
=> [week7-BAEKJOON] 별찍기-2, 최댓값, 숫자의 개수, 문자열 반복

programmers/han/week8/week8-문자열내p와y의개수.py, programmers/han/week8/week8-자릿수더하기.py, programmers/han/week8/week8-자연수뒤집어배열로만들기.py
=> [week8-PROGRAMMERS] 문자열내 p와 y의 개수, 자연수 뒤집어 배열로 만들기, 자릿수 더하기

programmers/chaeeun/week8_12934.py
=> [week8-PROGRAMMERS] 정수 제곱근 판별

programmers/chaeeun/week8_12933.py
👉 O(nlogn)
자릿수를 리스트에 저장 => O(n)
sort => O(nlogn)
리스트 join => O(n)
내림차순은 `reverse=True`
`join`은 구분자와 리스트 순서도 헷갈렸다.
=> [week8-PROGRAMMERS] 정수 내림차순으로 배치하기

programmers/han/week8/week8-자연수뒤집어배열로만들기.py, programmers/han/week8/week8-정수내림차순으로배치하기.py, programmers/han/week8/week8-정수제곱근판별.py
[week8-PROGRAMMERS] 자연수뒤집어배열로만들기, 정수내림차순으로배치하기, 정수제곱근판별
O(n) => 아직은 보통 인자 값으로 넘어온 값의 길이만큼의 시간복잡도가 걸린다.
=> [week8-PROGRAMMERS] 자연수뒤집어배열로만들기, 정수내림차순으로배치하기, 정수제곱근판별

programmers/han/week8/week8-하샤드수.py
=> [week8-PROGRAMMERS] 하샤드 수

programmers/han/week9/두정수사이의합.py, programmers/han/week9/서울에서 김서방 찾기.py, programmers/han/week9/콜라츠추측.py
=> [week8-PROGRAMMERS] 두 정수 사이의 합, 서울에서 김서방 찾기, 콜라즈 추측

programmers/chaeeun/week9_12912.py
👉 O(n)
range: n(big - small)개의 정수 생성
sum: n의 개수만큼 더함
=> [week9-PROGRAMMERS] 두 정수 사이의 합

programmers/chaeeun/week9_12919.py
=> [week9-PROGRAMMERS] 서울에서 김서방 찾기

programmers/chaeeun/week9_12943.py
=> [week9-PROGRAMMERS] 콜라츠 추측

programmers/han/week9/나누어 떨어지는 숫자 배열.py
＃ [week8-PROGRAMMERS] 나누어 떨어지는 숫자 배열
Ｏ(n) => 배열의 길이만큼
=> [week8-PROGRAMMERS] 나누어 떨어지는 숫자 배열

baekjoon/seongdeok/1074-Z.py
=> [BAEKJOON] Z

programmers/chaeeun/week9_12910.py
=> [week9-PROGRAMMERS] 나누어 떨어지는 숫자 배열

baekjoon/seongdeok/1074-Z.py, programmers/han/week9/제일 작은 수 제거하기.py, programmers/han/week9/핸드폰 번호 가리기.py
=> [week9-PROGRAMMERS] 제일 작은 수 제거하기, 핸드폰 번호 가리기

programmers/chaeeun/week9_12948.py
=> [week9-PROGRAMMERS] 핸드폰 번호 가리기

programmers/chaeeun/week9_12935.py
=> [week9-PROGRAMMERS] 제일 작은 수 제거하기

programmers/han/week9/없는 숫자 더하기.py, programmers/han/week9/음양 더하기.py
=> [week9-PROGRAMMERS] 없는 숫자 더하기, 음양 더하기

programmers/chaeeun/week9_76501.py
=> [week9-PROGRAMMERS] 음양 더하기

programmers/chaeeun/week9_86051.py
=> [week9-PROGRAMMERS] 없는 숫자 더하기

programmers/chaeeun/week9_70128.py
=> [week9-PROGRAMMERS] 내적

programmers/chaeeun/week9_12922.py
=> [week9-PROGRAMMERS] 수박수박수박수박수박수?

programmers/chaeeun/week10_12903.py
=> [week10-PROGRAMMERS] 가운데 글자 가져오기

programmers/han/week9/week9-내적.py, programmers/han/week9/week9-수박수박수박수물음표.py
[week9-PROGRAMMERS] 내적, 수박수박수박수박수박수?
O(n)
=> [week9-PROGRAMMERS] 내적, 수박수박수박수박수박수?

programmers/han/week10/week10-가운데 글자 가져오기.py, programmers/han/week10/week10-약수의 개수와 덧셈.py
[week10-PROGRAMMERS] 가운데 글자 가져오기, 약수의 개수와 덧셈
**< 약수의 개수와 덧셈 >**
```python
import math
def solution(left, right):
answer = 0
for i in range(left, right + 1, 1):
sqrt = math.sqrt(i)
if int(sqrt) == sqrt:
answer -= i
else:
answer += i
return answer
```
=> [week10-PROGRAMMERS] 가운데 글자 가져오기, 약수의 개수와 덧셈

programmers/chaeeun/week10_77884.py
👉 O(루트n * (right-left + 1))
홀짝만 알거면 그냥 제곱수인지 판별하면 될듯
=> [week10-PROGRAMMERS] 약수의 개수와 덧셈

programmers/han/week10/week10-문자열 내림차순으로 배치하기.py, programmers/han/week10/week10-부족한 금액 계산하기.py
=> [week10-PROGRAMMERS] 문자열 내림차순으로 배치하기, 부족한 금액 계산하기

programmers/chaeeun/week10_12918.py
👉 O(N)
`s.isdigit()`으로 하면 간단하다
=> [week10-PROGRAMMERS] 문자열 다루기 기본

programmers/han/week10/week10-문자열 다루기 기본.py, programmers/han/week10/week10-직사각형 별찍기.py, programmers/han/week10/week10-최대공약수 최소공배수.py, programmers/han/week10/week10-행렬의 덧셈.py
[week10-PROGRAMMERS] 문자열 다루기 기본, 직사각형 별찍기, 최대공약수 최소공배수, 행렬의 덧셈
O(n)
=> [week10-PROGRAMMERS] 문자열 다루기 기본, 직사각형 별찍기, 최대공약수 최소공배수, 행렬의 덧셈

programmers/chaeeun/week10_12950.py
=> [week10-PROGRAMMERS] 행렬의 덧셈

programmers/chaeeun/week10_12969.py
=> [week10-PROGRAMMERS] 직사각형 별찍기

programmers/chaeeun/week10_12940.py
👉 유클리드 알고리즘 시간복잡도 log(min(n, m))
lcm 함수는 버전이 맞지 않아서 못 사용했다. 3.9이상부터 가능!
=> [week10-PROGRAMMERS] 최대공약수와 최소공배수

programmers/chaeeun/week10_12906.py
=> [week10-PROGRAMMERS] 같은 숫자는 싫어

programmers/chaeeun/week10_68935.py
=> [week10-PROGRAMMERS] 3진법 뒤집기

programmers/chaeeun/week10_12982.py
=> [week10-PROGRAMMERS] 예산

programmers/chaeeun/week10_12930.py
=> [week10-PROGRAMMERS] 이상한 문자 만들기

programmers/han/week10/week10-3진법 뒤집기.py, programmers/han/week10/week10-같은 숫자는 싫어.py
=> [week10-PROGRAMMERS] 3진법 뒤집기, 같은 숫자는 싫어

programmers/han/week10/week10-예산.py, programmers/han/week10/week10-이상한 문자열 만들기.py
=> [week10-PROGRAMMERS] 예산, 이상한 문자열 만들기

programmers/han/week11/week11 - 2016.py, programmers/han/week11/week11 - 시저 암호.py, programmers/han/week11/week11 - 포켓몬.py
=> [week11-PROGRAMMERS] 2016, 시저 암호, 포켓몬

programmers/chaeeun/week11_12926.py
👉 O(len(s))
chr()은 아스키코드 -> 문자열
ord()는 문자열 -> 아스키코드
=> [week11-PROGRAMMERS] 시저 암호

programmers/chaeeun/week11_1845.py
👉 O(N)
set()으로 바로 list를 set으로 만들어주다니
=> [week11-PROGRAMMERS] 폰켓몬

programmers/chaeeun/week11_12977.py
👉 O(n^3)
`combinations()` 너무 편하다.
=> [week11-PROGRAMMERS] 소수 만들기

programmers/han/week11/week11 - 다트 게임.py, programmers/han/week11/week11 - 비밀지도.py, programmers/han/week11/week11 - 소수 만들기.py
=> [week11-PROGRAMMERS] 다트 게임, 비밀지도, 소수 만들기

programmers/chaeeun/week11_42576.py
=> [week11-PROGRAMMERS] 완주하지 못한 선수

programmers/chaeeun/week11_42748.py
O(n*nlogn)
슬라이싱: O(n)
sorting: O(nlogn)
=> [week11-PROGRAMMERS] K번째수

baekjoon/chaeeun/week11_17681.py
=> [week11-PROGRAMMERS] [1차] 비밀지도

programmers/chaeeun/week11_17682.py
=> [week11-PROGRAMMERS] [1차] 다트 게임

programmers/han/week11/week11 - K번째수.py, programmers/han/week11/week11 - 모의고사.py, programmers/han/week11/week11 - 완주하지 못한 선수.py
=> [week11-PROGRAMMERS] k-번째수, 모의고사, 완주하지 못한 선수

programmers/han/week11/week11 - 체육복.py
[week11-PROGRAMMERS] 체육복.py
O(n)
=> [week11-PROGRAMMERS] 체육복.py

programmers/chaeeun/week11_42862.py
👉 O(n^2)
리스트[:]는 슬라이싱 연산자로 리스트의 복사본을 생성한다는 사실!
=> [week11-PROGRAMMERS] 체육복

programmers/han/week11/week11 - 실패율.py, programmers/han/week11/week11 - 크레인 인형뽑기 게임.py
[week11-PROGRAMMERS] 실패율, 크레인 인형뽑기 게임
O(N)
- 실패율 문제에서 실패율을 구하는 공식에서 (현재 스테이지 참여 인원 / (총원 - 이전 레벨 참여자)) 분모가 0이 될 수 있음을 간과 함.
스테이지 참여 총원과 이전 레벨을 통과한 인원이 같을 수 있음
=> [week11-PROGRAMMERS] 실패율, 크레인 인형뽑기 게임

programmers/han/week12/삼총사.py, programmers/han/week12/크기가 작은 부분 문자열.py
O(n)
삼총사에 나온 Combination 라이브러리를 파이썬에서 제공! 원리는 외워 두는 것이 좋아보임
=> [week12-PROGRAMMERS] 삼총사, 크기가 작은 부분 문자열

programmers/chaeeun/week11_64061.py
👉 O(M * R)
len(moves) * len(board)
=> [week11-PROGRAMMERS] 크레인 인형뽑기 게임

programmers/chaeeun/week12_131705.py, programmers/chaeeun/week12_147355.py
삼총사 👉 O(n^3)
크기가 작은 부분 문자열 👉 O(n)
`itertools.combinations`
=> [week12_PROGRAMMERS] 삼총사

programmers/han/week12/week12 - 두 개 뽑아서 더하기.py, programmers/han/week12/week12 - 삼총사.py, programmers/han/week12/week12 - 푸드 파이트 대회.py
[week12-PROGRAMMERS] 두 개 뽑아서 더하기, 푸드 파이트 대회
O(ｎ^log(n))
=> [week12-PROGRAMMERS] 두 개 뽑아서 더하기, 푸드 파이트 대회

programmers/chaeeun/week12_86491.py
=> [week12-PROGRAMMERS] 최소직사각형

programmers/chaeeun/week12_81301.py
=> [week12-PROGRAMMERS] 숫자 문자열과 영단어

programmers/chaeeun/week12_142086.py
=> [week12-PROGRAMMERS] 가장 가까운 같은 글자

programmers/chaeeun/week12_134240.py
👉 O(N)
생각해보니 for문을 2번 쓸 필요는 없는 거 같다.
```python
for j in range(food[i] // 2):
front += str(i)
```
는 `front += str(i) * (food[i] // 2)`로 대체해도 될듯
=> [week12-PROGRAMMERS] 푸드 파이트 대회

programmers/han/week12/week12 - 명예의 전당(1).py, programmers/han/week12/week12 - 추억 점수.py, programmers/han/week12/week12 - 콜라 문제.py
[week12-PROGRAMMERS] 콜라 문제, 추억 점수, 명예의 전당(1)
Ｏ（ｎ）
=> [week12-PROGRAMMERS] 콜라 문제, 추억 점수, 명예의 전당(1)

programmers/han/week13/week13-과일장수.py, programmers/han/week13/week13-기사단원의 무기.py
[week13-PROGRAMMERS] 과일장수, 기사단원의 무기
O(n)
=> [week13-PROGRAMMERS] 과일장수, 기사단원의 무기

programmers/chaeeun/week12_132267.py
=> [week12-PROGRAMMERS] 콜라 문제

programmers/chaeeun/week12_176963.py
=> [week12-PROGRAMMERS] 추억 점수

programmers/chaeeun/week12_135808.py
=> [week12-PROGRAMMERS] 카드 뭉치

programmers/chaeeun/week12_138477.py
=> [ week12-PROGRAMMERS] 명예의 전당

programmers/han/week13/week13-기사단원의 무기.py, programmers/han/week13/week13-소수찾기.py
[week13-PROGRAMMERS] 소수찾기
O(N)
=> [week13-PROGRAMMERS] 소수찾기

programmers/han/week13/week13-덧칠하기.py, programmers/han/week13/week13-옹알이.py
[week13-PROGRAMMERS] 덧칠하기, 옹알이
O(n)
옹알이 문제 -> " " 공백 replcae 의미 기억하기
=> [week13-PROGRAMMERS] 덧칠하기, 옹알이

programmers/han/week13/week13-로또의 최고 순위와 최저 순위.py, programmers/han/week13/week13-문자열 나누기.py, programmers/han/week13/week13-숫자 짝궁.py
[week13-PROGRAMMERS] 로또의 최고 순위와 최저 순위, 문자열 나누기, 숫자 짝꿍
O(n)
숫자 짝꿍 문제 다시 시도해보기 틀렸음 모르겠어서 답지 참고함
=> [week13-PROGRAMMERS] 로또의 최고 순위와 최저 순위, 문자열 나누기, 숫자 짝꿍

programmers/chaeeun/week13_12921.py
👉 O(nloglogn)
아리스토테네스의 체의 시간복잡도는 loglogn이라는데요...!
=> [week13-PROGRAMMERS] 소수 찾기

programmers/chaeeun/week13_161989.py
=> [week13-PROGRAMMERS] 덧칠하기

programmers/chaeeun/week13_133499.py
=> [week13-PROGAMMERS] 옹알이

programmers/chaeeun/week13_77484.py
=> [week13-PROGRAMMERS] 로또의 최고 순위와 최저 순위

programmers/chaeeun/week13_140108.py
=> [week13-PROGRAMMERS] 문자열 나누기

programmers/han/week13/week13-대충 만든 자판.py, programmers/han/week13/week13-둘만의 암호.py
[week13-PROGRAMMERS] 대충 만든 자판, 둘만의 암호
=> [week13-PROGRAMMERS] 대충 만든 자판, 둘만의 암호

programmers/han/week13/week13 - 9번 이웃한 칸.py
[week13-PROGRAMMERS] 9번 이웃한 칸
O(n)
=> [week13-PROGRAMMERS] 9번 이웃한 칸

programmers/han/week13/week13-햄버거 만들기.py
=> [week13-PROGRAMMERS] 햄버거 만들기

programmers/han/week13/week13-숫자 짝궁.py, programmers/han/week14/카드 뭉치.py
[week13, 14] 숫자 짝꿍, 카드 뭉치
O(n)
=> [week13, 14] 숫자 짝꿍, 카드 뭉치

programmers/chaeeun/week13_131128.py
👉 O(n + m)
실패 코드
```python
def solution(X, Y):
answer = ''
arrX = list(X)
arrY = list(Y)
common = []
for char in arrX:
if char in arrY:
common.append(char)
arrY.remove(char)
if len(arrY) == 0:
break
if len(common) == 0:
return "-1"
common.sort(reverse=True)
result = ''.join(common)
number = int(result)
return str(number)
```
=> [week13-PROGRAMMERS] 숫자 짝꿍

programmers/chaeeun/week13_155652.py
=> [week13-PROGRAMMERS] 둘만의 암호

programmers/han/week14/키패드 누르기.py
[week14-PROGRAMMERS] 키패드 누르기
아나 ㅜㅜ 틀려서 답지 참고
=> [week14-PROGRAMMERS] 키패드 누르기

programmers/chaeeun/week13_250125.py
=> [week13-PROGRAMMERS] [PCCE 기출문제] 9번 / 이웃한 칸

programmers/chaeeun/week13_160586.py
=> [week13-PROGRAMMERS] 대충 만든 자판

programmers/han/week14/week14-성격 유형 검사하기.py
[week14-PROGRAMMERS] 성격 유형 검사하기
O(n)
=> [week14-PROGRAMMERS] 성격 유형 검사하기

programmers/han/week14/week14-신규 아이디 추천.py
[week14-PROGRAMMERS] 신규 아이디 추천
O(n^log2) ??
어렵진 않았지만 노가다여서 ㅜㅜ
내 힘으로 풀어내서 뿌듯했다
=> [week14-PROGRAMMERS] 신규 아이디 추천

programmers/han/week14/wekk14-바탕화면.py
[week14-PROGRAMMERS] 바탕화면
O(n)
=> [week14-PROGRAMMERS] 바탕화면

programmers/han/week14/week14-개인정보 수집 유효기간.py, programmers/han/week14/week14-달리기 경주.py
[week14-PROGRAMMERS] 개인정보 수집 유효기간, 달리기 경주
O(n) 
둘 다 틀림 일단 답지 참고하여 다시 풀어보기
=> [week14-PROGRAMMERS] 개인정보 수집 유효기간, 달리기 경주

programmers/chaeeun/week14_150370.py
=> [week14-PROGRAMMERS] 개인정보 수집 유효기간

programmers/han/week14/week14-붕대 감기.py, programmers/han/week14/week14-신고결과 받기.py
[week14-PROGRAMMERS] 신고결과 받기, 붕대 감기
O(n) 
실력이 늘은 건지 문제가 쉬웠던건지 구분이 안감 ㅋㅋㅋ
=> [week14-PROGRAMMERS] 신고결과 받기, 붕대 감기

programmers/han/week14/week14-가장 많이 받은 선물.py, programmers/han/week14/week14-붕대 감기.py
[week14-PROGRAMMERS] 가장 많이 받은 선물
O(n^log2)
노가다 문제 ㅜㅜㅜ
=> [week14-PROGRAMMERS] 가장 많이 받은 선물

programmers/han/Level 2/1.최대값과 최소값.py, programmers/han/Level 2/2.올바른 괄호.py, programmers/han/Level 2/3.최솟값 만들기.py
[PROGRAMMERS-LEVEL2] 
1.최대값과 최솟값 
2. 올바른 괄호 
3. 최솟값 만들기
DFS 트리 구조 안되면 그냥 외우기
=> [PROGRAMMERS-LEVEL2] 1.최대값과 최솟값 2. 올바른 괄호 3. 최솟값 만들기

programmers/han/Level 2/3.최솟값 만들기.py
3. 최솟값 만들기
O(n)
와우 처음에 순열로 풀었다가 -> 내림차순 정렬 * 오름차순 정렬의 합이 최소 값이라는 사실을 처음 알았다. 
사람들 너무 똑똑한거 같다...
=> [PROGRAMMERS-LEVEL2] 3. 최솟값 만들기

programmers/han/Level 2/4.JadenCase 문자열 만들기.py
[PROGRAMMERS-LEVEL2] 4.JadenCase 문자열 만들기
O(n)
공백도 문자열이 될 수 있음을 간과
알파벳인지 확인해주는 함수 isalpha() 가 있다는 사실.
=> [PROGRAMMERS-LEVEL2] 4.JadenCase 문자열 만들기

programmers/han/Level 2/5.이진 변환 반복하기.py
[PROGRAMMERS-LEVEL2] 5.이진 변환 반복하기
O(n^logN)
=> [PROGRAMMERS-LEVEL2] 5.이진 변환 반복하기

programmers/han/Level 2/6.숫자의 표현.py, programmers/han/Level 2/7.다음 큰 숫자.py
[PROGRAMMERS-LEVEL2] 6.숫자의 표현 7. 다음 큰 숫자
O(logN)
문제를 꼼꼼히 숙지하고 잔 실수를 줄이자
=> [PROGRAMMERS-LEVEL2] 6.숫자의 표현 7. 다음 큰 숫자

.vscode/settings.json, Han.session.sql, programmers/han/Level 2/7.다음 큰 숫자.py, programmers/han/Level 2/8.피보나치 수.py
[PROGRAMMERS-LEVEL2] 7. 다음 큰 숫자 other way 8. 피보나치 수
+ MySQL VSC 연동 및 MYSQL 2단계 풀이
O(n)
1234567을 나눈 나머지를 구하는 이유는 찾아봐야하는 데
return 값이 32비트 중 가장 첫 비트로 넘어 가버리면 맨 첫 비트는 부호 비트로 음수로 변하게 된다 singed integer 따라서 자연스럽게 2의 보수 계산으로 음수로 넘어가 버리는것을 막기 위한 최 효율의 숫자를 나누고 나머지를 반환 받는 것으로 기억함.
=> [PROGRAMMERS-LEVEL2] 7. 다음 큰 숫자 other way 8. 피보나치 수

Han.session.sql, programmers/han/Level 2/9.짝지어 제거하기.py
[PROGRAMMERS-LEVEL2] 9. 짝지어 제거하기 + SQL 문제 풀이
O(n)
replace는 효율면에서 지양하는 것이 바람직 하다
=> [PROGRAMMERS-LEVEL2] 9. 짝지어 제거하기 + SQL 문제 풀이

Han.session.sql, programmers/han/Level 2/10. 카펫.py
[PROGRAMMERS-LEVEL2] 10. 카펫 + SQL 문제 풀이
O(sqrt(N))
우선적으로 직사각형이 돼야 함을 간과함 정신차리자..
=> [PROGRAMMERS-LEVEL2] 10. 카펫 + SQL 문제 풀이

Han.session.sql, programmers/han/Level 2/11. 점프와 순간 이동.py
[PROGRAMMERS-LEVEL2] 11. 점프와 순간 이동 + SQL 문제 풀이
Ｏ(N)
생각 안나서 GPT 참고함 다시 복습 필요!!
=> [PROGRAMMERS-LEVEL2] 11. 점프와 순간 이동 + SQL 문제 풀이

Han.session.sql, programmers/han/Level 2/11. 점프와 순간 이동.py, programmers/han/Level 2/12. 구명보트.py
[PROGRAMMERS-LEVEL2] 12. 구명보트 + SQL 문제 풀이 + 11 복습
O(n)
탐욕 문제는 최우선 정렬한 뒤 생각하는 습관을 길러보자
=> [PROGRAMMERS-LEVEL2] 12. 구명보트 + SQL 문제 풀이 + 11 복습

programmers/han/Level 2/12. 구명보트.py
=> [PROGRAMMERS-LEVEL2] 12. 구명보트

Han.session.sql, programmers/han/Level 2/13. 멀리 뛰기.py
[PROGRAMMERS-LEVEL2] 13. 멀리 뛰기
O(n)
n+1 마다의 경우의 수 패턴을 활용한 동적 계획법 문제
=> [PROGRAMMERS-LEVEL2] 13. 멀리 뛰기 + MySql 문제

programmers/han/Level 2/14. N개의 최소공배수.py
[PROGRAMMERS-LEVEL2] 14. N개의 최소공배수.py
O(N^logn)
LCM = a * b / GCD
GCD = 유클리드 호제법(a, b) 
n개의 LCM => a * b / GCD(LCM(a1, a2), b) ...
=> [PROGRAMMERS-LEVEL2] 14. N개의 최소공배수.py

programmers/han/Level 2/[12. 13. 14.] 복습.py
[REPEAT][PROGRAMMERS-LEVEL2] 12, 13, 14 문제 복습
복습!
=> [REPEAT][PROGRAMMERS-LEVEL2] 12, 13, 14 문제 복습

programmers/han/Level 2/18.연속 부분 수열 합의 개수.py
[PROGRAMMERS-LEVEL2] 18. 연속 부분 수열 합의 개수
O(n^2)
- 원형 리스트 문제 효율을 위해 x2를 해준다
- set 메서드 활용
=> [PROGRAMMERS-LEVEL2] 18. 연속 부분 수열 합의 개수

programmers/han/Level 2/18.연속 부분 수열 합의 개수.py, programmers/han/Level 2/19.괄호 회전하기.py
[PROGRAMMERS-LEVEL2] 19. 괄호 회전
O(n^2)
다시 풀어보기
=> [PROGRAMMERS-LEVEL2] 19. 괄호 회전

programmers/han/Level 2/19.괄호 회전하기.py, programmers/han/Level 2/20. 할인 행사.py
[PROGRAMMERS-LEVEL2] 19. 괄호 회전 복습, 20. 할인 행사
O(n^log)
아 제발 실수 좀 줄이자 j index에 i 변수를 사용하고 앉아있네 
헷갈릴 거 같으면 변수 이름을 아예 다르게 사용하던지 해야할듯
=> [PROGRAMMERS-LEVEL2] 19. 괄호 회전 복습, 20. 할인 행사

programmers/han/Level 2/20. 할인 행사.py
[PROGRAMMERS-LEVEL2][REPEAT] 20. 할인 행사
O(n * m)
저번에 시간복잡도 틀림. 그리고 이번엔 실수 안했다!
=> [PROGRAMMERS-LEVEL2][REPEAT] 20. 할인 행사

programmers/han/Level 2/[19, 18] 복습.py
[PROGRAMMERS-LEVEL2][REPEAT] 19. 괄호 회전하기, 18. 연속 부분 수열 합의 개수
O(N*M)
=> [PROGRAMMERS-LEVEL2][REPEAT] 19. 괄호 회전하기, 18. 연속 부분 수열 합의 개수

programmers/han/Level 2/21. n^2 배열.py, programmers/han/Level 2/[17, 16, 15, 14, 13] 복습.py
[PROGRAMMERS-LEVEL2] 21. n^2 배열
[PROGRAMMERS-LEVEL2][REPEAT]  17.예상 대진표, 16. 멀리 뛰기, 15. 귤 고르기, 14. 구명보트 복습
O(n - m)
- n^2의 시간복잡도를 n - m 의 시간복잡도로 줄여 풀이가 가능하도록 하는 의도
- 다양한 수학적 사고 필요 (배열은 보통 //, %의 패턴으로 풀이가 가능하다.)
=> [PROGRAMMERS-LEVEL2] 21. n^2 배열 / [PROGRAMMERS-LEVEL2][REPEAT]  17.예상 대진표, 16. 멀리 뛰기, 15. 귤 고르기, 14. 구명보트 복습

programmers/han/Level 2/21. n^2 배열.py
[PROGRAMMERS-LEVEL2][REPEAT]  21. n^2 배열
복습
=> [PROGRAMMERS-LEVEL2][REPEAT]  21. n^2 배열

programmers/han/Level 2/22.행렬의 곱셈.py
[PROGRAMMERS-LEVEL2] 22. 행렬의 곱셈
O(n^3)
암산하기 좀 복잡했는데 나중에 설명할 때 편하기 위해서라도 체계화를 어떻게 할 지 고민해 볼 필요도 있어 보임
=> [PROGRAMMERS-LEVEL2] 22. 행렬의 곱셈

programmers/han/Level 2/24. cache[1차].py
[PROGRAMMERS-LEVEL2] 24. cache[1차].py
O(N)
대소문자 구분 안함 이런 문구를 제대로 확인해야함
=> [PROGRAMMERS-LEVEL2] 24. cache[1차].py

programmers/han/Level 2/25. 의상.py
[PROGRAMMERS-LEVEL2] 24. 해쉬.py
O(n)
복습 필수
=> [PROGRAMMERS-LEVEL2] 24. 해쉬.py

programmers/han/Level 2/26. 기능개발.py
[PROGRAMMERS-LEVEL2] 26. 기능개발.py
O(N)
=> [PROGRAMMERS-LEVEL2] 26. 기능개발.py

programmers/han/Level 2/25. 의상.py
Cherry pick commit (파일 명칭 수정)
[PROGRAMMERS-LEVEL2] 24. 해쉬.py ->
[PROGRAMMERS-LEVEL2] 25. 의상.py
=> Cherry pick "[PROGRAMMERS-LEVEL2] 25. 의상.py"

programmers/han/Level 2/27. 피로도.py
[PROGRAMMERS-LEVEL2] 27. 피로도.py
O(logN)
조합, 경우의 수, 순열 자면서도 풀 수 있을 정도로 뿌셔오기!
개념부터 다시 잡기 수학 문제 마스터하기.
무조건
=> [PROGRAMMERS-LEVEL2] 27. 피로도.py

programmers/han/Level 2/[22 ~ 27] 복습.py
[PROGRAMMERS-LEVEL2][REPEAT] 25. 의상, 27. 피로도
- 경우의 수
- 순환
=> [PROGRAMMERS-LEVEL2][REPEAT] 25. 의상, 27. 피로도

programmers/han/Level 2/[22 ~ 27] 복습.py
[PROGRAMMERS-LEVEL2][REPEAT] 26. [1차] 캐쉬
- 조합 복습
- LRU 문제
=> [PROGRAMMERS-LEVEL2][REPEAT] 26. [1차] 캐쉬

programmers/han/Level 2/28. 튜플.py
[PROGRAMMERS-LEVEL2] 28. 튜플
O(n^2)
- 문제가 쫌 그런데... 이겨내자
=> [PROGRAMMERS-LEVEL2] 28. 튜플

programmers/han/Level 2/29. 프로세스.py
[PROGRAMMERS-LEVEL2] 29. 프로세스.py
O(N)
이건 쉬움 큐/스택은 많이 해봐서 그런가 쉬운 듯 다른 알고리즘도 많이 
반복해서 풀고 활용하도록 하자
=> [PROGRAMMERS-LEVEL2] 29. 프로세스.py

programmers/han/Level 2/30. 전화번호 목록.py
[PROGRAMMERS-LEVEL2] 30. 전화번호 목록.py
O(N)
- 접두사, 접미어 문제 startswith, endswith
- sort() 는 문자열의 크기로 ascending 되기 때문에 길이의 sort가 아닌 문자열로 sort 되어야 한다.
=> [PROGRAMMERS-LEVEL2] 30. 전화번호 목록.py

programmers/han/Level 2/31. 뉴스 클러스터링.py
PROGRAMMERS-LEVEL2] 31. 뉴스 클러스터링.py
O(N)
문제를 잘못 이해함. -> 내일 다시 풀어보기
=> PROGRAMMERS-LEVEL2] 31. 뉴스 클러스터링.py

programmers/han/Level 2/31. 뉴스 클러스터링.py
[PROGRAMMERS-LEVEL2] 31. 뉴스 클러스터링.py
O(N)
- 문제 잘 확인하기 ab+ 들어 왔을 때 b+ 버린다는 의미는 즉, 미리 특수문자를 제거하고 jacard에 넣는 것이 아닌 for문을 돌면서 체크 후 버릴지 넣을지를 판단한다는 의미다. 문제 꼼꼼히 읽기
=> [PROGRAMMERS-LEVEL2] 31. 뉴스 클러스터링.py

programmers/han/Level 2/32. 타겟 넘버.py
[PROGRAMMERS-LEVEL2] 32. 타겟 넘버
- BFS / DFS 연습
- 가장 많이 나오는 DFS 형태
O(2^n)
- 가장 많이 나오는 DFS 형태 무조건 외워두기
=> [PROGRAMMERS-LEVEL2] 32. 타겟 넘버

programmers/han/Level 2/32. 타겟 넘버.py, programmers/han/Level 2/33.게임 맵 최단거리.py
[PROGRAMMERS-LEVEL2] 33. 게임 맵 최단거리
O(???)
- 32. 타겟 넘버 복습
- 33. 게임 맵 최단거리 실패 -> 해답 보고 외우기!!! 무조건 필히 많이 나오는 문제
=> [PROGRAMMERS-LEVEL2] 33. 게임 맵 최단거리

programmers/han/Level 2/33.게임 맵 최단거리.py, programmers/han/Level 2/[32, 33] 복습.py
[PROGRAMMERS-LEVEL2][REPEAT] 32. 타겟 넘버, 33. 게임 맵 최단거리
??? -> 뭐지 헷갈리네 n^2 인지 2^n 인지 확인해보기
- 시간 복잡도 확인해 보고 dfs -> bfs로 bfs -> dfs로도 풀어보는 연습 해보기
- 복습
=> [PROGRAMMERS-LEVEL2][REPEAT] 32. 타겟 넘버, 33. 게임 맵 최단거리

programmers/han/Level 2/34.롤케이크 자르기.py
[PROGRAMMERS-LEVEL2] 34. 롤케이크 자르기
O(N)
- 첫 풀이에서 효율이 나지 않았던 원인 분석
- set() 객체를 for문 안에서 만들면 효율이 안 나기 때문에 딕셔너리로 중복을 직접 체크하도록 하여 문제 해결
=> [PROGRAMMERS-LEVEL2] 34. 롤케이크 자르기

programmers/han/Level 2/35. 방문 길이.py
[PROGRAMMERS-LEVEL2] 35. 방문 길이
O(N)
**(A → B)**와 **(B → A)**가가 동일한 경로임을 간과
경로 문제에서는 직선인지 양방향인지 유념해 두기
=> [PROGRAMMERS-LEVEL2] 35. 방문 길이

programmers/han/Level 2/37. K진수에서 소수 개수 구하기.py
[PROGRAMMERS-LEVEL2] 37. K진수에 소수 개수 구하기
O(logN * 2)
<너무 좋은 문제!> -> TODO 복습
1. 소수 판별 문제
2. 진수 변환 문제
3. 리터럴 활용 문제
=> [PROGRAMMERS-LEVEL2] 37. K진수에 소수 개수 구하기

programmers/han/Level 2/38.압축.py
[PROGRAMMERS-LEVEL2] 38. 압축
O(n^logN)
- LZW 알고리즘
- ING
=> [PROGRAMMERS-LEVEL2] 38. 압축

programmers/han/Level 2/40.뒤에 있는 큰 수 찾기.py
[PROGRAMMERS-LEVEL2] 40. 뒤에 있는 큰 수 찾기
O(N)
- 스택 문제
- 너무 좋은 문제 복습하기.
=> [PROGRAMMERS-LEVEL2] 40. 뒤에 있는 큰 수 찾기

baekjoon/seongdeok/bronze/AxB_10998.py, baekjoon/seongdeok/bronze/숫자의 합_11720.py
[BAEKJOON] AxB, 숫자의 합
- O(1), O(n/2)
- 너무 쉬움
=> [BAEKJOON] AxB, 숫자의 합

baekjoon/seongdeok/bronze/A+B-C.py, baekjoon/seongdeok/bronze/알람 시계.py
[BAEKJOON] A+B-C, 알람 시계
O(1)
음 너무 쉬움
=> [BAEKJOON] A+B-C, 알람 시계

baekjoon/seongdeok/bronze/최소, 최대.py
[BAEKJOON] 최소, 최대
O(N)
- spilt() 컴플리핸션으로 받으면 편하다.
=> [BAEKJOON] 최소, 최대

baekjoon/seongdeok/bronze/ACM 호텔.py, baekjoon/seongdeok/bronze/나머지_3052.py, baekjoon/seongdeok/bronze/음계_2920.py
[BAEKJOON] 나머지, 음계
O(N)
- easy
=> [BAEKJOON] 나머지, 음계

baekjoon/seongdeok/bronze/문자와 문자열_27866.py, baekjoon/seongdeok/bronze/소수 찾기_1978.py, baekjoon/seongdeok/bronze/알파벳 찾기_10809.py, baekjoon/seongdeok/silver/괄호_9012.py, baekjoon/seongdeok/silver/나이순 정렬_10814.py, baekjoon/seongdeok/silver/단어정렬_1181.py, baekjoon/seongdeok/silver/수 정렬하기2_2751.py, baekjoon/seongdeok/silver/좌표 정렬하기_11650.py
[BAEKJOON] 좌표 정렬하기, 나이 순 정렬, 수 정렬1-2, 단어 정렬, 괄호 복습
O(n, log n)
- Silver 승급
=> [BAEKJOON] 좌표 정렬하기, 나이 순 정렬, 수 정렬1-2, 단어 정렬, 괄호 복습

baekjoon/seongdeok/bronze/블랙잭_2798.py, baekjoon/seongdeok/bronze/팰린드롬수_1259.py
[BAEKJOON] 블랙잭, 팰린드롬수
- O(nCr)
- O(N)
- 조합 풀이 문제
- 문자열 슬라이싱 문제
=> [BAEKJOON] 블랙잭, 팰린드롬수

baekjoon/seongdeok/silver/수 찾기2_10816.py, baekjoon/seongdeok/silver/수 찾기_1920.py, baekjoon/seongdeok/silver/스택_10828.py, baekjoon/seongdeok/silver/체스판 다시 칠하기_1018.py, baekjoon/seongdeok/silver/카드2_2164.py, baekjoon/seongdeok/silver/팩토리얼 0의 개수_1676.py
[BAEKJOON] 체스판, 수 찾기, 카드 2, 수 찾기 2, 팩토리얼, 스택
O(n)
- 시간 복잡도 -> set 
- 시간 복잡도 -> list 대신 deque 활용
=> [BAEKJOON] 체스판, 수 찾기, 카드 2, 수 찾기 2, 팩토리얼, 스택

baekjoon/seongdeok/gold/회의실 배정_1931.py, baekjoon/seongdeok/silver/1로 만들기_1463.py, baekjoon/seongdeok/silver/ATM_90575.py, baekjoon/seongdeok/silver/듣보잡_1764.py, baekjoon/seongdeok/silver/쉬운 최단거리_14940.py, baekjoon/seongdeok/silver/피보나치 함수_1003.py
[BAEKJOON] 회의실 배정 ~ 1로 만들기
- Dynamic Programing and BFS, DFS 완전 탐색 -> 시간 복잡도 효율을 높이기 위해 DP 및 Memorization을 우선적으로 확인할 것.
=> [BAEKJOON] 회의실 배정 ~ 1로 만들기

programmers/han/Level 2-3/1.최대값과 최소값.py
=> [PROGRAMMERS] 1번 문제 복습
